### ISSUE TITLE
2D Campos dataset demo 

### ISSUE THREAD

**Issue by lperozzi** [xinwucwp/osv#1]
Hi Xinming,

first many thanks to make available your code. It is very appreciate. 
My question: I tried to run the 2D Campos dataset demo, but I have systematically an error:

```
setupForSubset: campos
scan for approximate fault orientations...
Exception in thread "AWT-EventQueue-0" 	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at edu.mines.jtk.io.ArrayInputAdapter.readFloats(ArrayInputAdapter.java:452)
	at edu.mines.jtk.io.ArrayInputAdapter.readFloats(ArrayInputAdapter.java:465)
	at edu.mines.jtk.io.ArrayInputAdapter.readFloats(ArrayInputAdapter.java:475)
	at edu.mines.jtk.io.ArrayInputAdapter.readFloats(ArrayInputAdapter.java:485)
	at edu.mines.jtk.io.ArrayInputStream.readFloats(ArrayInputStream.java:384)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

java.io.EOFException: java.io.EOFException
```

The only modification I'have made is to replace the input seismic image (`gxl`) with the seismic data `gx373`at line 15 of `demoCampos.py `. Have you an idea where I'm worng?

Many thanks for your help

Lorenzo

**Comment by xinwucwp** [comment]
Hi Lorenzo,

This error means you did not get the dimensions correct for the input data.

Regards,
Xinming

**Comment by lperozzi** [comment]
Hi,
many thanks for your prompt reply. This means we have to update the `n1` and `n2` values in `utils.py` for the `name=="campos"`, with the values of the `gx373.dat`dataset (i.e.: `n1=300, n2=550`) right? I still have the same error.

Many thanks again
Lorenzo

**Comment by lperozzi** [comment]
Hi,

I test the new `demoFault2D.py` and all works well. But it requires the `ft.dat` input file. What this file is exactely? I tried to run on my 2D section but I have an error message that say he needs `ft.dat`

```
Exception in thread "AWT-EventQueue-0" 	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at edu.mines.jtk.io.ArrayInputStream.<init>(ArrayInputStream.java:54)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.python.core.PyReflectedConstructor.constructProxy(PyReflectedConstructor.java:210)

java.io.FileNotFoundException: java.io.FileNotFoundException: ../../data/2d/GG8702/ft.dat
```

Actually I give only the binary seismic as input file.

Have you some suggestions?

Many thanks for your work

Lorenzo

**Comment by xinwucwp** [comment]
please uncomment the steps of goLinearity and goFaultOrientScan to go through the full process. ft.dat is generated in these two steps.

**Comment by xinwucwp** [comment]
You might want to pay some attention to read the python code to have a general idea of the whole process

**Comment by lperozzi** [comment]
Many thanks for your help.
